// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace TangConvert
{
	public class DbAnimation
	{
		public string name;
		public double fadeInTime;
		public int duration;
    public double scale;
		public int loop;
    public int tweenEarsing;
    public DbTimeline[] timeline;

		public DbAnimation ()
		{
		}
	}
}

