// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
namespace TangConvert
{
  public class DbArmature
  {

    public string name;

    public List<DbBone> bone;
    public List<DbSkin> skin;
    public List<DbAnimation> animation;

    public DbArmature ()
    {
    }
  }
}

