// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangConvert
{
  public class DbColorTransform
  {

    public int aO;
    public int rO;
    public int gO;
    public int bO;
    public double aM;
    public double rM;
    public double gM;
    public double bM;

    public DbColorTransform ()
    {

    }
  }
}

