// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangConvert
{
  public class DbTimeline
  {
    public string name;
    public double scale;
    public double offset;

    public DbFrame[] frame;
    public DbTimeline ()
    {
    }
  }
}

