// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TangConvert
{
  public class SpineSkeleton
  {

    public string name;
    public List<SpineBone> bones;
    public List<SpineSlot> slots;
    public Dictionary<string, Dictionary<string, Dictionary<string, SpineSkin>>> skins;
    public Dictionary<string, Dictionary<string, Dictionary<string, SpineAnimation>>> animations;

    public SpineSkeleton ()
    {
    }
  }
}

