// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangConvert
{
  public class DbFrame
  {
    public int duration;
    public string eventName;
    public string soundName;
    public string action;
    public string hide;
    public float tweenEarsing;
    public float tweenRotation;
    public string displayIndex;
    public float z;

    public DbTransform transform;
    public DbColorTransform colorTransform;

    public DbFrame ()
    {
    }
  }
}

