// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangConvert
{
  public class DbTransform
  {
    public float x;
    public float y;
    public float skX;
    public float skY;
    public float scX;
    public float scY;
    public float pX;
    public float pY;

    public DbTransform ()
    {
    }
  }
}

