// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace TangConvert
{
  [DataContract]
  public class DragonBones
  {
    [DataMember]
    public string name;
    [DataMember]
    public int frameRate;
    [DataMember]
    public string version;
    [DataMember]
    public List<DbArmature> armature;

  }
}

