// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using TangUI;

namespace TangGame
{
	public class UIContext
	{

		// ****************** panels *******************
		public const string MAIN_POPUP_PANEL_NAME = "MainPopupPanel";
		public const string HERO_VIEW_PANEL_NAME = "HeroViewPanel";

		public const string HERO_ITEM_NAME = "HeroItem";

		public static UIPanelNodeManager mgr; 

		public static string getWidgetsPath(string weightName){
			return TangUI.Config.WIDGET_PATH + "/" + weightName;
		}
	}
}

