// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using DragonBones;
using DragonBones.Factorys;
using DragonBones.Animation;
using DragonBones.Objects;
using DragonBones.Display;
using DragonBones.Textures;
using Com.Viperstudio.Utils;
using UnityEngine;

namespace TangDragonBones
{
  public class DbgoManager : MonoBehaviour
  {
    public delegate void ResEventHandler(object sender, ResEventArgs a);
    public static event ResEventHandler RaiseLoadedEvent;

    private static Queue<string> requireQueue = new Queue<string> ();
    private UnityFactory factory = null;

    void Awake ()
    {
      //Application.targetFrameRate = 30;
      factory = new UnityFactory ();
    }
    // Update is called once per frame
    void Update ()
    {

      if (requireQueue.Count > 0) {

        string name = requireQueue.Dequeue ();

        // 确认数据和资源在缓存中
        if (Cache.characterDataTable.ContainsKey (name)) {

          AvatarData data = Cache.characterDataTable [name];

          if (factory.GetSkeletonData (name) == null) {
            factory.AddSkeletonData (data.skeletonData, data.skeletonData.Name);
          }

          if (factory.GetTextureAtlas (name) == null) {
            factory.AddTextureAtlas (data.textAtlas);
          }

          Armature armature = factory.BuildArmature (name, null, name);
          GameObject heroObj = new GameObject ();
          heroObj.name = armature.Name;
          GameObject armatureGobj = (armature.Display as UnityArmatureDisplay).Display;
          armatureGobj.transform.parent = heroObj.transform;
          armatureGobj.transform.localPosition = Vector3.zero;
          armatureGobj.transform.localRotation = Quaternion.identity;
          DragonBonesBhvr bhvr = heroObj.AddComponent<DragonBonesBhvr> ();
          bhvr.armature = armature;
          heroObj.SetActive (false);
          Add (heroObj);

          // 发出通知事件，游戏对象已经准备完毕
          if (RaiseLoadedEvent != null)
            RaiseLoadedEvent (null, new ResEventArgs(name));

        } else {

          Debug.LogError ("DragonBones res " + name + " not ready.");

        }
      }


      WorldClock.Clock.AdvanceTime (Time.deltaTime);
    }

    #region GameObject Methods

    /// <summary>
    /// 加载角色游戏对象
    /// </summary>
    /// <param name="name">Name.</param>
    public static void LazyLoad (string name)
    {

      if (Cache.characterDataTable.ContainsKey (name)) {

        // 有了
        OnResReady (name);

      } else if (Config.use_packed_res) {

        // 从资源包下载
        Tang.AssetBundleLoader.LoadAsync (name, OnAbLoaded);

      } else {

        // 本地读取
        ResourceLoad (name);
      }
    }

    /// <summary>
    /// 加载多个英雄游戏对象
    /// </summary>
    /// <param name="hero">Hero.</param>
    /// <param name="count">Count.</param>
    public static void LazyLoad (string name, int count)
    {
      for (int i = 0; i < count; i++)
        LazyLoad (name);
    }

    /// <summary>
    /// 从 AssetBundle 加载资源
    /// </summary>
    /// <param name="ab">Ab.</param>
    private static void OnAbLoaded (AssetBundle ab)
    {
      Debug.Log ("OnResLoaded");
      if (ab != null) {

        string atlasFilepath = ab.name + "_atlas";
        string textureFilepath = ab.name + "_texture";
        string skeletonFilepath = ab.name + "_skeleton";

        TextAsset atlasAssets = ab.Load (atlasFilepath, typeof(TextAsset)) as TextAsset;
        Texture textureAssets = ab.Load (textureFilepath, typeof(Texture)) as Texture;
        TextAsset skeletonAssets = ab.Load (skeletonFilepath, typeof(TextAsset)) as TextAsset;

        if (atlasAssets != null && textureAssets != null && skeletonAssets != null) {
          SetUp (ab.name, atlasAssets, textureAssets, skeletonAssets);
        }
      }

    }

    /// <summary>
    /// 从本地 Resources 文件夹中加载资源
    /// </summary>
    /// <param name="name">Name.</param>
    private static void ResourceLoad (string name)
    {
      Debug.Log ("ResourceLoad");

      string atlasFilepath = Config.DATA_PATH + Tang.Config.DIR_SEP + name + "_atlas";
      string textureFilepath = Config.DATA_PATH + Tang.Config.DIR_SEP + name + "_texture";
      string skeletonFilepath = Config.DATA_PATH + Tang.Config.DIR_SEP + name + "_skeleton";

      TextAsset atlasAssets = Resources.Load (atlasFilepath, typeof(TextAsset)) as TextAsset;
      Texture textureAssets = Resources.Load (textureFilepath, typeof(Texture)) as Texture;
      TextAsset skeletonAssets = Resources.Load (skeletonFilepath, typeof(TextAsset)) as TextAsset;

      if (atlasAssets != null && textureAssets != null && skeletonAssets != null) {
        SetUp (name, atlasAssets, textureAssets, skeletonAssets);
      }

    }

    private static void SetUp (string name, TextAsset atlasAssets, Texture textureAssets, TextAsset skeletonAssets)
    {

      Debug.Log ("SetUp");

      // 内容加载成功

      // 分析 skeleton 数据
      // read and parse skeleton josn into SkeletonData
      TextReader reader = new StringReader (skeletonAssets.text);
      Dictionary<string, System.Object> skeletonRawData = Json.Deserialize (reader) as Dictionary<string, System.Object>;
      SkeletonData skeletonData = ObjectDataParser.ParseSkeletonData (skeletonRawData);

      // 分析 Atlas 数据
      // read and parse texture atlas josn into TextureAtlas
      reader = new StringReader (atlasAssets.text);
      Dictionary<string, System.Object> atlasRawData = Json.Deserialize (reader) as Dictionary<string, System.Object>;
      AtlasData atlasData = AtlasDataParser.ParseAtlasData (atlasRawData);

      // 保存数据到缓存中
      if (skeletonData != null && atlasData != null) {
        Cache.characterDataTable.Add (name, new AvatarData (skeletonData, new TextureAtlas (textureAssets, atlasData)));
      }

      // 资源准备完毕
      OnResReady (name);
    }

    /// <summary>
    /// 资源准备完毕
    /// </summary>
    /// <param name="name">Name.</param>
    private static void OnResReady (string name)
    {

      // 将游戏对象创建请求放入队列中，在 Update 方法中完成创建
      requireQueue.Enqueue (name);

    }

    /// <summary>
    /// 获取一个游戏对象－没有被使用的
    /// </summary>
    /// <param name="name">Name.</param>
    public static GameObject FetchUnused (string name)
    {

      if (Cache.gobjTable.ContainsKey (name)) {
        foreach (GameObject gobj in Cache.gobjTable[name]) {
          if (gobj != null && !gobj.activeSelf) {
            gobj.SetActive (true);
            return gobj;
          }
        }
      }

      return null;
    }

    /// <summary>
    /// Add the specified gobj.
    /// </summary>
    /// <param name="gobj">Gobj.</param>
    public static void Add (GameObject gobj)
    {
      if (Cache.gobjTable.ContainsKey (gobj.name)) {
        Cache.gobjTable [gobj.name].Add (gobj);
      } else {
        List<GameObject> list = new List<GameObject> ();
        list.Add (gobj);
        Cache.gobjTable.Add (gobj.name, list);
      }
    }

    /// <summary>
    /// 释放游戏对象所占用的资源
    /// </summary>
    /// <param name="gobj">Gobj.</param>
    /// <param name="all">If set to <c>true</c> all.</param>
    public static void Release (GameObject gobj, bool all)
    {
      string name = gobj.name;
      gobj.SetActive (false);
      if (all) {
        // 从对象表中删除
        if (Cache.gobjTable.ContainsKey (name)) {
          Cache.gobjTable [name].Remove (gobj);
          if (Cache.gobjTable [name].Count == 0) {
            Cache.gobjTable.Remove (name);
          }
        }
        // 销毁对象
        GameObject.Destroy (gobj);
        // 销毁资源包
        Tang.AssetBundleLoader.Unload (name, all);
      }
    }

    /// <summary>
    /// 有多少个游戏对象可用
    /// </summary>
    /// <param name="name">对象名称</param>
    public static int SizeOfUnused (string name)
    {
      if (Cache.gobjTable.ContainsKey (name)) {
        int size = 0;
        List<GameObject> list = Cache.gobjTable [name];
        foreach (GameObject o in list) {
          if (!o.activeSelf)
            size++;
        }
        return size;
      }
      return 0;
    }

    /// <summary>
    /// 有多少个 GameObject
    /// </summary>
    /// <returns>The of.</returns>
    /// <param name="name">Name.</param>
    public static int SizeOf (string name)
    {
      if (Cache.gobjTable.ContainsKey (name)) {
        List<GameObject> list = Cache.gobjTable [name];
        return Cache.gobjTable [name].Count;
      }
      return 0;
    }

    #endregion
  }
}

