// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;

namespace TangLevel
{
  public class Config
  {
    public static bool use_packed_res = false;

    public const string BATTLE_BG_PATH = "Prefabs/Level/BattleBg";

    public static Dictionary<int, Level> levelTable = new Dictionary<int, Level>();

    public static void MockData(){

      Level level = new Level ();
      level.id = 1;
      level.name = "Test Level 1";

      level.subLeves = new SubLevel[3];
      for (int i = 1; i < 4; i++) {
        SubLevel subLevel = new SubLevel ();
        subLevel.id = i;
        subLevel.resName = "bbg_arena";
        level.subLeves [i - 1] = subLevel;

      }

      levelTable.Add (level.id, level);
    }


  }
}

