// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;

namespace TangLevel
{
  public class Config
  {

    /// <summary>
    /// 地图右边界
    /// </summary>
    public const float RIGHT_BOUND = 70;

    /// <summary>
    /// 缺省攻击的动画剪辑
    /// </summary>
    public const string DEFAULT_ATTACK_CLIP = "attack";

    /// <summary>
    ///   是否使用打包后的资源
    /// </summary>
    public static bool use_packed_res = false;

    /// <summary>
    /// 战斗背景资源路径
    /// </summary>
    public const string GOBJS_PATH = "Prefabs/Gobjs";
    public static string GobjsPath(string name){
      return GOBJS_PATH + Tang.Config.DIR_SEP + name;
    }

    /// <summary>
    /// 关卡表
    /// </summary>
    public static Dictionary<int, Level> levelTable = new Dictionary<int, Level> ();
    /// <summary>
    /// 技能表
    /// </summary>
    public static Dictionary<int, Skill> skillTable = new Dictionary<int, Skill> ();
    /// <summary>
    /// 作用器表
    /// </summary>
    public static Dictionary<int, Effector> effectorTable = new Dictionary<int, Effector> ();

  }
}

