// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangLevel
{
  public class LevelContext
  {

    public static Level CurrentLevel {
      get;
      set;
    }

    public static SubLevel CurrentSubLevel {
      get;
      set;
    }

    public static SubLevel NextSubLevel {
      get;
      set;
    }

    public static bool IsNextSubLevelResReady {
      get;
      set;
    }

    public static bool IsWaitingForEnten {
      get;
      set;
    }

  }
}

