// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using TS = TangScene;

namespace TangLevel
{
  public class LevelHelper
  {

    public static Level CurrentLevel{
      get;
      set;
    }

    public static SubLevel CurrentSubLevel {
      get;
      set;
    }


    public static void LoadSubLevel(SubLevel subLevel){



    }


    public static void OnLevelCompleted(){

    }

    
    /*
    private void StartLoadRes ()
    {
      if (!Config.use_packed_res)
        LoadResComplete (null);
      else {
        string path = Tang.ResourceUtils.GetAbFilePath ( CurrentSubLevel.resName );
        TS.TS.LoadAssetBundle (path, LoadResComplete);      
      }
    }
    private void LoadResComplete (WWW www)
    { 
      UnityEngine.Object assets = null;
      if (www == null)
        assets = Resources.Load (Config.PANEL_PATH + Tang.Config.DIR_SEP + name);
      else
        assets = www.assetBundle.Load (name);
      gameObject = GameObject.Instantiate (assets) as GameObject;
      
      if (gameObject != null) {
        gameObject.name = name;
        context.cache.Put (name, gameObject);
        
        DynamicBindUtil.BindScriptAndProperty (gameObject, name);
        
        Show ();    
      }
      
    }*/

  }
}

