// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace TangLevel
{
  public class Hero
  {

    public delegate void HpChangeHandler (int val, int max);
    public HpChangeHandler raiseHpChange;

    public delegate void MpChangeHandler(int val, int max);
    public MpChangeHandler raiseMpChange;

    // --- 人物属性 ---
    #region Character Attributes
    /// <summary>
    /// 资源名称
    /// </summary>
    public string resName;
    /// <summary>
    /// 力量
    /// </summary>
    public int strength;
    /// <summary>
    /// 智力
    /// </summary>
    public int intelligence;
    /// <summary>
    /// 敏捷
    /// </summary>
    public int agility;
    /// <summary>
    /// 最大生命值
    /// </summary>
    public int maxHp;
    /// <summary>
    /// 生命值
    /// </summary>
    private int m_hp;
    public int hp {
      get{ return m_hp; }
      set{
        m_hp = value;
        if (raiseHpChange != null) {
          raiseHpChange (value, maxHp);
        }
      }
    }
    /// <summary>
    /// 最大能量值
    /// </summary>
    public int maxMp;
    /// <summary>
    /// 能量值
    /// </summary>
    private int m_mp;
    public int mp {
      get{ return m_mp; }
      set{
        m_mp = value;
        if (raiseMpChange != null) {
          raiseMpChange (value, maxMp);
        }
      }
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int grade;

    /// <summary>
    /// 战斗前布阵所站的位置 - 前，中，后
    /// </summary>
    public BattlePos battlePos;

    /// <summary>
    /// 攻击距离
    /// </summary>
    public int attackDistance;
    /// <summary>
    /// 英雄的 AI，可以有多个
    /// </summary>
    public string[] ai;
    /// <summary>
    /// 英雄技能
    /// </summary>
    public List<Skill> skills;
    #endregion


    // --- 场景属性 ---
    #region Scene Attribute
    /// <summary>
    /// 出生点
    /// </summary>
    public Vector2 birthPoint;
    /// <summary>
    /// 战斗方向
    /// </summary>
    public BattleDirection battleDirection;
    #endregion


    #region Constroctor
    public Hero ()
    {

    }
    #endregion
  }
}

