// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace TangLevel
{
  public class SubLevel
  {
    public int id;

    public int index;

    public string resName;

    public Group enemyGroup;

    public SubLevel ()
    {

    }
  }
}
